models:

  app.tree:
    properties:
      byRelationship:
        field:
          type: core.property.field.string

  app.storage.column:
    properties:
      identifier:
        field:
          type: core.property.field.boolean
      mappedBy:
        field:
          type: core.property.field.string
      inversedBy:
        field:
          type: core.property.field.string
      composition:
        field:
          type: core.property.field.boolean
          defaultValue: false
      orderBy:
        field:
          type: core.property.field.string

  app.ui.translation:
    properties:
      label:
        field:
          type: core.property.field.string

  app.ui.sluggable:
    parent: core.extension.property.computed
    properties:
      field:
        field:
          type: core.property.field.string

  app.view:
    properties:
      template:
        field:
          type: core.property.field.string
      userSpecifiedContent:
        field:
          type: core.property.field.boolean
          defaultValue: true

  app.view.container_view:
    parent: app.view

  app.view.detail_view:
    parent: app.view

  app.view.form_view:
    parent: app.view
    properties:
      form:
        classType:
          className: Symfony\Component\Form\Form

  app.view.list_view:
    parent: app.view
    properties:
      entities:
        collection: []
      model:
        relationship:
          type: core.property.relationship.toOne
          target: core.model

  app.view.tree_view:
    parent: app.view.list_view