models:

  storage.column:
    properties:
      identifier:
        field:
          type: app_gear.core_bundle.entity.property.field.boolean
      mappedBy:
        field:
          type: app_gear.core_bundle.entity.property.field.string
      inversedBy:
        field:
          type: app_gear.core_bundle.entity.property.field.string

  ui.translation:
    properties:
      label:
        field:
          type: app_gear.core_bundle.entity.property.field.string

  ui.sluggable:
    parent: app_gear.core_bundle.entity.extension.property.computed
    properties:
      field:
        field:
          type: app_gear.core_bundle.entity.property.field.string

  view:
    properties:
      template:
        field:
          type: app_gear.core_bundle.entity.property.field.string

  view.list_view:
    parent: view
    properties:
      entities:
        collection: []

  view.detail_view:
    parent: view

  view.model_view:
    parent: view
    properties:
      model:
        relationship:
          type: app_gear.core_bundle.entity.property.relationship.toOne
          target: app_gear.core_bundle.entity.model

  view.model_view.form_view:
    parent: view
    properties:
      form:
        classType:
          className: Symfony\Component\Form\Form

  view.container_view:
    parent: view