services:

  appgear.controller:
    abstract: true
    class: AppGear\AppBundle\Controller\AbstractController
    arguments:
      - '@appgear.storage'
      - '@app_gear.core.model.manager'
      - '@appgear.view.manager'
      - '@appgear.security.manager'
    calls:
      - [setContainer, ['@service_container']]

  appgear.controller.form:
    parent: appgear.controller
    class: AppGear\AppBundle\Controller\FormController
    arguments:
      - '@appgear.form.builder'
      - '@logger'

  appgear.controller.remove:
    parent: appgear.controller
    class: AppGear\AppBundle\Controller\RemoveController

  appgear.controller.view:
    parent: appgear.controller
    class: AppGear\AppBundle\Controller\ViewController

  appgear.controller.test:
    class: AppGear\AppBundle\Controller\TestController
    arguments:
      - '@appgear.storage'