services:

  appgear.entity_extension.sluggable:
    class: AppGear\AppBundle\EntityExtension\Sluggable
    tags:
      - name: extension.property.computed
        model: app_gear.app_bundle.entity.ui.sluggable

  appgear.entity_service.property.field.datetime_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\DateTimeTypeService
    tags:
      - name: form.property.field.service
        field: app_gear.core_bundle.entity.property.field.datetime

  appgear.entity_service.property.field.text_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\TextTypeService
    tags:
      - name: form.property.field.service
        field: app_gear.core_bundle.entity.property.field.text

  appgear.entity_service.view.view_service:
    class: AppGear\AppBundle\EntityService\View\ViewService
    arguments:
      - @templating
    tags:
      - name: appgear.entity_service.view
        model: app_gear.app_bundle.entity.view

  appgear.entity_service.view.detail_view_service:
    class: AppGear\AppBundle\EntityService\View\DetailViewService
    arguments:
      - @templating
      - @appgear.storage
      - @app_gear.core.model.manager
    tags:
      - name: appgear.entity_service.view
        model: app_gear.app_bundle.entity.view.detail_view

  appgear.entity_service.view.form_view_service:
    class: AppGear\AppBundle\EntityService\View\FormViewService
    arguments:
      - @templating
    tags:
      - name: appgear.entity_service.view
        model: app_gear.app_bundle.entity.view.form_view