services:

  appgear.entity_service.property.field.boolean_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\BooleanTypeService
    tags:
      - name: form.property.field.service
        field: core.property.field.boolean_type
      - name: storage.platform.mysql.property.field.service
        field: core.property.field.boolean_type

  appgear.entity_service.property.field.datetime_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\DateTimeTypeService
    tags:
      - name: form.property.field.service
        field: core.property.field.datetime_type
      - name: storage.platform.mysql.property.field.service
        field: core.property.field.datetime_type

  appgear.entity_service.property.field.float_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\FloatTypeService
    tags:
      - name: storage.platform.mysql.property.field.service
        field: core.property.field.float_type

  appgear.entity_service.property.field.integer_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\IntegerTypeService
    tags:
      - name: storage.platform.mysql.property.field.service
        field: core.property.field.integer_type

  appgear.entity_service.property.field.markdown_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\MarkdownTypeService
    tags:
      - name: form.property.field.service
        field: core.property.field.markdown_type
      - name: storage.platform.mysql.property.field.service
        field: core.property.field.markdown_type

  appgear.entity_service.property.field.text_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\TextTypeService
    tags:
      - name: form.property.field.service
        field: core.property.field.text_type
      - name: storage.platform.mysql.property.field.service
        field: core.property.field.text_type