services:

  appgear.entity_extension.sluggable:
    class: AppGear\AppBundle\EntityExtension\Sluggable
    tags:
      - name: extension.property.computed
        model: app.ui.sluggable

  appgear.entity_service.property.field.boolean_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\BooleanTypeService
    tags:
      - name: form.property.field.service
        field: core.property.field.boolean
      - name: storage.platform.mysql.property.field.service
        field: core.property.field.boolean

  appgear.entity_service.property.field.datetime_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\DateTimeTypeService
    tags:
      - name: form.property.field.service
        field: core.property.field.datetime
      - name: storage.platform.mysql.property.field.service
        field: core.property.field.datetime

  appgear.entity_service.property.field.float_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\FloatTypeService
    tags:
      - name: storage.platform.mysql.property.field.service
        field: core.property.field.float

  appgear.entity_service.property.field.integer_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\IntegerTypeService
    tags:
      - name: storage.platform.mysql.property.field.service
        field: core.property.field.integer

  appgear.entity_service.property.field.markdown_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\MarkdownTypeService
    tags:
      - name: form.property.field.service
        field: core.property.field.markdown
      - name: storage.platform.mysql.property.field.service
        field: core.property.field.markdown

  appgear.entity_service.property.field.text_type_servce:
    class: AppGear\AppBundle\EntityService\Property\Field\TextTypeService
    tags:
      - name: form.property.field.service
        field: core.property.field.text
      - name: storage.platform.mysql.property.field.service
        field: core.property.field.text

  appgear.entity_service.view.view_service:
    class: AppGear\AppBundle\EntityService\View\ViewService
    arguments:
      - '@templating'
    tags:
      - name: appgear.entity_service.view
        model: app.view

  appgear.entity_service.view.detail_view_service:
    class: AppGear\AppBundle\EntityService\View\DetailViewService
    arguments:
      - '@templating'
      - '@app_gear.core.model.manager'
    tags:
      - name: appgear.entity_service.view
        model: app.view.detail_view

  appgear.entity_service.view.form_view_service:
    class: AppGear\AppBundle\EntityService\View\FormViewService
    arguments:
      - @templating
    tags:
      - name: appgear.entity_service.view
        model: app.view.form_view