services:

  appgear.form.builder:
    class: AppGear\AppBundle\Form\FormBuilder
    arguments:
      - '@form.factory'
      - '@app_gear.core.model.manager'
      - '@app_gear.core.tagged_manager'
      - '@appgear.storage'

  appgear.form.manager:
    class: AppGear\AppBundle\Form\FormManager
    arguments:
      - '@appgear.form.builder'
      - '%appgear.application.upload.directory%'
      - '%appgear.application.upload.file_prefix%'

  appgear.form.type.markdown:
    class: AppGear\AppBundle\Form\Type\MarkdownType
    tags:
      - { name: form.type, alias: markdown }