services:

  appgear.form.builder:
    class: AppGear\AppBundle\Form\FormBuilder
    arguments:
      - @form.factory
      - @app_gear.core.model.manager
      - @app_gear.core.tagged_manager
      - @appgear.storage

  appgear.form.type.markdown:
    class: AppGear\AppBundle\Form\Type\MarkdownType
    tags:
      - { name: form.type, alias: markdown }