appgear.update:
  path: /update/{model}/{id}
  defaults:
    _controller: appgear.controller.update:updateAction
  requirements:
    model: '[a-zA-Z0-9_\.-]+'
    id: \d+
  methods: [POST]

appgear.remove:
  path: /remove/{model}/{id}
  defaults:
    _controller: appgear.controller.remove:removeAction
  requirements:
    model: '[a-zA-Z0-9_\.-]+'
    id: \d+
  methods: [POST]