parameters:
  memcache.host: localhost
  memcache.port: 11211

services:

  appgear.cache.cache_manager:
      class: AppGear\AppBundle\Cache\CacheManager
      arguments:
        - @doctrine.cache.memcache

  doctrine.cache.memcache:
    class: Doctrine\Common\Cache\MemcacheCache
    calls:
      - [setMemcache, [@memcache]]

  memcache:
    class: Memcache
    calls:
      - [addserver, [%memcache.host%, %memcache.port%]]

  appgear.view.manager:
    class: AppGear\AppBundle\View\ViewManager
    arguments:
      - @app_gear.core.model.manager
      - @app_gear.core.tagged_manager
      - @service_container

  appgear.twig.common_extension:
      class: AppGear\AppBundle\Twig\CommonExtension
      tags:
          - { name: twig.extension }

  appgear.twig.php_extension:
      class: AppGear\AppBundle\Twig\PhpExtension
      arguments:
        - %app_gear_app.twig.php_extension.available_functions%
      tags:
          - { name: twig.extension }

  appgear.twig.translation_extension:
      class: AppGear\AppBundle\Twig\TranslationExtension
      tags:
          - { name: twig.extension }

  appgear.twig.view_extension:
      class: AppGear\AppBundle\Twig\ViewExtension
      arguments:
          - @service_container
          - @appgear.view.manager
          - @app_gear.core.model.manager
      tags:
          - { name: twig.extension }