parameters:
  memcache.host: localhost
  memcache.port: 11211

services:

  appgear.cache.cache_manager:
      class: AppGear\AppBundle\Cache\CacheManager
      arguments:
        - @doctrine.cache.memcache

  doctrine.cache.memcache:
    class: Doctrine\Common\Cache\MemcacheCache
    calls:
      - [setMemcache, [@memcache]]

  memcache:
    class: Memcache
    calls:
      - [addserver, [%memcache.host%, %memcache.port%]]

  appgear.storage.proxy_cache_warmer:
    class: AppGear\AppBundle\Storage\CacheWarmer\ProxyCacheWarmer
    arguments:
      - @doctrine.orm.entity_manager
      - @app_gear.core.model.manager
    tags:
    - { name: kernel.cache_warmer, priority: 0 }

  appgear.controller.crud:
    class: AppGear\AppBundle\Controller\CrudController
    arguments:
      - @appgear.storage
      - @app_gear.core.model.manager
      - @appgear.view.manager
      - @appgear.form.builder
    calls:
      - [setContainer, ['@service_container']]

  appgear.storage:
    class: AppGear\AppBundle\Storage\Storage
    arguments:
      - @appgear.storage.driver.doctrine_orm
      - @app_gear.core.model.manager

  appgear.storage.driver.doctrine_orm:
    class: AppGear\AppBundle\Storage\Driver\DoctrineOrm\Driver
    arguments:
      - @doctrine.orm.entity_manager
      - @app_gear.core.model.manager

  appgear.storage.driver.doctrine_phpcr:
    class: AppGear\AppBundle\Storage\Driver\DoctrinePhpCr\Driver
    arguments:
      - @doctrine_phpcr
      - @appgear.storage.driver.doctrine_phpcr.proxy_manager

  appgear.storage.proxy_manager_abstract:
    class: AppGear\AppBundle\Storage\ProxyManagerAbstract
    abstract: true
    arguments:
     - %kernel.cache_dir%
     - @app_gear.core.model.manager

  appgear.storage.driver.doctrine_phpcr.proxy_manager:
    class: AppGear\AppBundle\Storage\Driver\DoctrinePhpCr\ProxyManager
    parent: appgear.storage.proxy_manager_abstract

  appgear.view.manager:
    class: AppGear\AppBundle\View\ViewManager
    arguments:
      - @app_gear.core.model.manager
      - @app_gear.core.tagged_manager
      - @service_container

  appgear.twig.common_extension:
      class: AppGear\AppBundle\Twig\CommonExtension
      tags:
          - { name: twig.extension }

  appgear.twig.php_extension:
      class: AppGear\AppBundle\Twig\PhpExtension
      arguments:
        - %app_gear_app.twig.php_extension.available_functions%
      tags:
          - { name: twig.extension }

  appgear.twig.translation_extension:
      class: AppGear\AppBundle\Twig\TranslationExtension
      tags:
          - { name: twig.extension }

  appgear.twig.view_extension:
      class: AppGear\AppBundle\Twig\ViewExtension
      arguments:
          - @appgear.view.manager
          - @appgear.cache.cache_manager
      tags:
          - { name: twig.extension }