parameters:
  memcache.host: localhost
  memcache.port: 11211

services:

  appgear.view.manager:
    class: AppGear\AppBundle\View\ViewManager
    arguments:
      - @twig
      - @appgear.view.handler.list

  appgear.view.handler.list:
    class: AppGear\AppBundle\View\Handler\ListHandler
    arguments:
    - @appgear.security.manager

  appgear.twig.common_extension:
      class: AppGear\AppBundle\Twig\CommonExtension
      tags:
          - { name: twig.extension }

  appgear.twig.translation_extension:
      class: AppGear\AppBundle\Twig\TranslationExtension
      tags:
          - { name: twig.extension }

  appgear.twig.view_extension:
      class: AppGear\AppBundle\Twig\ViewExtension
      arguments:
          - @service_container
          - @app_gear.core.model.manager
          - @appgear.security.manager
      tags:
          - { name: twig.extension }