services:

  appgear.storage:
    class: AppGear\AppBundle\Storage\Storage
    arguments:
      - '@appgear.storage.driver.manager'
      - '@app_gear.core.model.manager'

  appgear.storage.driver.manager:
    class: AppGear\AppBundle\Storage\DriverManager
    arguments:
      - '@service_container'

  appgear.storage.driver.doctrine_orm:
    class: AppGear\AppBundle\Storage\Driver\DoctrineOrm\Driver
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@app_gear.core.model.manager'
    tags:
        - { name: appgear.storage.driver, alias: doctrine_orm }

  appgear.storage.driver.yaml:
    class: AppGear\AppBundle\Storage\Driver\Yaml\Driver
    arguments:
      - '@app_gear.core.model.manager'
    tags:
        - { name: appgear.storage.driver, alias: yaml }

  appgear.storage.driver.doctrine_orm.generator.listener:
    class: AppGear\AppBundle\Storage\Driver\DoctrineOrm\Generator\GeneratorListener
    tags:
        - { name: kernel.event_listener, event: 'appgear.core.model.generator.generate.after', method: addIdentifierProperty }

  appgear.storage.driver.doctrine_orm.metadata.appgear_model_driver:
    class: AppGear\AppBundle\Storage\Driver\DoctrineOrm\Metadata\AppGearModelDriver
    calls:
      - [setDriverManager, ['@appgear.storage.driver.manager']]
      - [setModelManager, ['@app_gear.core.model.manager']]
      - [setTaggedManager, ['@app_gear.core.tagged_manager']]