parameters:
  appgear.storage.driver.doctrine_orm.metadata.appgear_model_driver.supported_model_prefixes: []

services:

  appgear.storage:
    class: AppGear\AppBundle\Storage\Storage
    arguments:
      - '@appgear.storage.driver.manager'
      - '@app_gear.core.model.manager'

  appgear.storage.driver.manager:
    class: AppGear\AppBundle\Storage\DriverManager

  appgear.storage.driver.doctrine_orm:
    class: AppGear\AppBundle\Storage\Driver\DoctrineOrm\Driver
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@app_gear.core.model.manager'
    tags:
        - { name: appgear.storage.driver, alias: doctrine_orm }

  appgear.storage.driver.yaml:
    class: AppGear\AppBundle\Storage\Driver\Yaml\Driver
    arguments:
      - '@appgear.storage.driver.yaml.loader'
      - '@appgear.storage.driver.hydrator.factory'
      - '@app_gear.core.model.manager'
    tags:
        - { name: appgear.storage.driver, alias: yaml }

  appgear.storage.driver.yaml.loader:
    class: AppGear\AppBundle\Storage\Driver\Yaml\Loader
    arguments:
      - '@kernel'

  appgear.storage.driver.hydrator.simple:
    class: AppGear\AppBundle\Storage\Driver\Yaml\Hydrator\SimpleHydrator

  appgear.storage.driver.hydrator.factory:
    class: AppGear\AppBundle\Storage\Driver\Yaml\HydratorFactory
    arguments:
      - '@appgear.storage.driver.hydrator.simple'

  appgear.storage.driver.doctrine_orm.generator.listener:
    class: AppGear\AppBundle\Storage\Driver\DoctrineOrm\Generator\GeneratorListener
    tags:
        - { name: kernel.event_listener, event: 'appgear.core.model.generator.generate.after', method: addIdentifierProperty }

  appgear.storage.driver.doctrine_orm.metadata.appgear_model_driver:
    class: AppGear\AppBundle\Storage\Driver\DoctrineOrm\Metadata\AppGearModelDriver
    calls:
      - [setModelManager, ['@app_gear.core.model.manager']]
      - [setTaggedManager, ['@app_gear.core.tagged_manager']]
      - [setSupportedModelPrefixes, ['%appgear.storage.driver.doctrine_orm.metadata.appgear_model_driver.supported_model_prefixes%']]